2018-03-29 00:00:17,636 [INFO] 1522299617: -----Experiment with CHAMP ------ 
2018-03-29 00:00:17,636 [INFO] 1522299617: -----------------------------Experiment ID 1522299617 begins--------------------------
2018-03-29 00:00:17,636 [INFO] 1522299617: Configuration of the experiment: no_experiments: 20
2018-03-29 00:00:17,636 [INFO] 1522299617: Configurations of the experiment: n_max_iters_experiment: 15
2018-03-29 00:00:17,636 [INFO] 1522299617: Configurations of the experiment: n_agents: 4
2018-03-29 00:00:17,636 [INFO] 1522299617: Configurations of the experiment: n_agents_tracking: 1
2018-03-29 00:00:17,636 [INFO] 1522299617: XXXXXXX                                                                        XXX  
X       X    X XXXXX  XXXXXX XXXXX     X   X    X XXXXXX X    X  XXXXX        X   X 
X        X  X  X    X X      X    X    X   XX  XX X      XX   X    X         X     X
XXXXX     XX   X    X XXXXX  X    X    X   X XX X XXXXX  X X  X    X         X     X
X         XX   XXXXX  X      XXXXX     X   X    X X      X  X X    X         X     X
X        X  X  X      X      X   X     X   X    X X      X   XX    X          X   X 
XXXXXXX X    X X      XXXXXX X    X    X   X    X XXXXXX X    X    X           XXX  


2018-03-29 00:00:17,636 [ERROR] root: Experiment failed
Traceback (most recent call last):
  File "/home/manish/Awesomestuff/AdHocTeamWork/AdHoc2/experiments/experiment_master_cp_champ.py", line 103, in <module>
    main_arena, agents = generate_init.generate_from_savedexperiment('data/e2',i,n_agents)
  File "/home/manish/Awesomestuff/AdHocTeamWork/AdHoc2/src/utils/generate_init.py", line 224, in generate_from_savedexperiment
    return generate_from_file(fname,n_agents)
  File "/home/manish/Awesomestuff/AdHocTeamWork/AdHoc2/src/utils/generate_init.py", line 190, in generate_from_file
    grid_matrix = np.load(open(arenafilename, 'r'))
IOError: [Errno 2] No such file or directory: 'data/e2/0/arena.npy'
2018-03-29 00:00:17,671 [INFO] twilio.http_client: POST Request: https://api.twilio.com/2010-04-01/Accounts/AC03c6c74162a11f07ffb0170da406f3c2/Messages.json
2018-03-29 00:00:17,671 [INFO] twilio.http_client: PAYLOAD: {'Body': "Experiment with args Namespace(ch_length_mean=20, ch_length_min=5, ch_length_sigma=10, ch_maxparticles=1000, ch_resample_particles=1000, mcts_setting='heuristic', settingsfolder='/home/manish/Awesomestuff/AdHocTeamWork/AdHoc2/data/e2') exception [Errno 2] No such file or directory: 'data/e2/0/arena.npy' ! Check logs!", 'To': '+15125022558', 'From': '+15126438645'}
2018-03-29 00:00:18,035 [INFO] twilio.http_client: POST Response: 201 {"sid": "SM39cfef791817464ab25708e4a6394670", "date_created": "Thu, 29 Mar 2018 05:00:17 +0000", "date_updated": "Thu, 29 Mar 2018 05:00:17 +0000", "date_sent": null, "account_sid": "AC03c6c74162a11f07ffb0170da406f3c2", "to": "+15125022558", "from": "+15126438645", "messaging_service_sid": null, "body": "Sent from your Twilio trial account - Experiment with args Namespace(ch_length_mean=20, ch_length_min=5, ch_length_sigma=10, ch_maxparticles=1000, ch_resample_particles=1000, mcts_setting='heuristic', settingsfolder='/home/manish/Awesomestuff/AdHocTeamWork/AdHoc2/data/e2') exception [Errno 2] No such file or directory: 'data/e2/0/arena.npy' ! Check logs!", "status": "queued", "num_segments": "3", "num_media": "0", "direction": "outbound-api", "api_version": "2010-04-01", "price": null, "price_unit": "USD", "error_code": null, "error_message": null, "uri": "/2010-04-01/Accounts/AC03c6c74162a11f07ffb0170da406f3c2/Messages/SM39cfef791817464ab25708e4a6394670.json", "subresource_uris": {"media": "/2010-04-01/Accounts/AC03c6c74162a11f07ffb0170da406f3c2/Messages/SM39cfef791817464ab25708e4a6394670/Media.json"}}
